version: '3.8'

services:
  heartbeat-server:
    image: luisnabais/heartbeat-server:latest
    container_name: heartbeat-server
    hostname: heartbeat-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NTFY_TOPIC=${NTFY_TOPIC}
      - NTFY_TOKEN=${NTFY_TOKEN}
      - HEARTBEAT_TIMEOUT=${HEARTBEAT_TIMEOUT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s