name: Auto Tag from VERSION

on:
  push:
    branches:
      - main
    paths:
      - VERSION
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: codeberg-tiny
    steps:
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.name "Forgejo Actions"
          git config user.email "actions@forgejo.org"

      - name: Get version from file
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GIT_ENV

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "refs/tags/${VERSION}" >/dev/null 2>&1; then
            echo "Tag ${VERSION} already exists."
            echo "tag_exists=true" >> $GIT_OUTPUT
          else
            echo "tag_exists=false" >> $GIT_OUTPUT
          fi

      - name: Create and push tag
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          git tag $VERSION
          git push origin $VERSION
