name: Build and push Docker image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: codeberg-tiny
    steps:
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Login no registry do Codeberg
        uses: https://code.forgejo.org/docker/login-action@v3
        with:
          registry: codeberg.org
          username: ${{ secrets.CODEBERG_USER }}
          password: ${{ secrets.CODEBERG_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            codeberg.org/${{ secrets.CODEBERG_USER }}/${{ github.repository }}:latest
            codeberg.org/${{ secrets.CODEBERG_USER }}/${{ github.repository }}:${{ github.ref_name }}
